#!/usr/bin/env python3
"""
Introspect the OpenStudio Python bindings and generate python-api.yaml (+ .gz).

The script requires the OpenStudio Python directory to be provided so that the
bindings can be imported at runtime.

Usage:
    python extract_python_api.py <openstudio_python_dir> [--output-dir <dir>]

    <openstudio_python_dir>  Path to the OpenStudio Python directory, e.g.
                             /Applications/OpenStudio-3.10.0/Python
    --output-dir             Where to write output files. Defaults to
                             <script_dir>/docs/api/ next to this script.
                             Files are named python-api-<version>.yaml/.yaml.gz.
"""

import argparse
import datetime
import gzip
import inspect
import re
import shutil
import sys
from pathlib import Path
from typing import Dict, List, Optional
import yaml


SUBMODULE_PREFIXES = {
    'model': 'openstudio.model',
    'openstudioutilitiesgeometry': 'openstudio.openstudioutilitiesgeometry',
    'openstudioutilitiesidf': 'openstudio.openstudioutilitiesidf',
    'openstudioutilitiesidd': 'openstudio.openstudioutilitiesidd',
    'openstudioutilitiessql': 'openstudio.openstudioutilitiessql',
    'openstudioutilitiestime': 'openstudio.openstudioutilitiestime',
    'openstudioutilitiesunits': 'openstudio.openstudioutilitiesunits',
    'measure': 'openstudio.measure',
    'energyplus': 'openstudio.energyplus',
    'gbxml': 'openstudio.gbxml',
}


def infer_return_type(method_name: str, params: List[str]) -> Optional[str]:
    """
    Infer return type from OpenStudio naming conventions — no live calls needed.
      is*/has*/can*/are*  (no params) -> bool
      set*(value)                     -> bool
      reset*/autocalculate*/autosize* -> None
      remove*/clear*                  -> None
    """
    if method_name.startswith(('is', 'has', 'can', 'are')):
        return 'bool'
    if method_name.startswith('set') and params:
        return 'bool'
    if method_name.startswith(('reset', 'autocalculate', 'autosize', 'remove', 'clear')):
        return 'None'
    return None


def get_mro_parent(cls) -> Optional[str]:
    for parent in cls.__mro__[1:]:
        if parent.__name__ != 'object':
            return parent.__name__
    return None


def extract_class(cls, submodule_prefix: str) -> Dict:
    """Extract own (non-inherited) methods for a single class."""
    parent = cls.__mro__[1] if len(cls.__mro__) > 1 else None
    parent_methods = set(dir(parent)) if parent else set()

    own_names = sorted(
        n for n in dir(cls)
        if not n.startswith('_') and n not in parent_methods
    )

    methods = []
    for name in own_names:
        obj = getattr(cls, name, None)
        if obj is None or not callable(obj):
            continue

        params = []
        try:
            sig = inspect.signature(obj)
            for pname in sig.parameters:
                if pname != 'self':
                    params.append(pname)
        except (ValueError, TypeError):
            pass

        return_type = infer_return_type(name, params)

        entry = {'name': name}
        if params:
            entry['parameters'] = params
        if return_type:
            entry['return_type'] = return_type
        methods.append(entry)

    return {
        'python_path': f'{submodule_prefix}.{cls.__name__}',
        'parent': get_mro_parent(cls),
        'own_method_count': len(methods),
        'methods': methods,
    }


def is_real_class(name: str, obj) -> bool:
    if not isinstance(obj, type):
        return False
    # Skip Vector/Optional wrappers generated by SWIG
    if name.endswith('Vector') or re.match(r'^Optional\w+$', name):
        return False
    return True


def extract_submodule(submodule, prefix: str) -> Dict:
    classes = {}
    for name in sorted(dir(submodule)):
        if name.startswith('_'):
            continue
        obj = getattr(submodule, name, None)
        if not is_real_class(name, obj):
            continue
        classes[name] = extract_class(obj, prefix)
    return classes


def _write_yaml_and_gz(data: dict, path: Path) -> None:
    """Write a YAML file and its gzip-compressed counterpart."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
    gz_path = path.with_suffix(path.suffix + '.gz')
    with open(path, 'rb') as f_in, gzip.open(gz_path, 'wb') as f_out:
        shutil.copyfileobj(f_in, f_out)
    print(f"  Written: {path}")
    print(f"  Written: {gz_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Introspect OpenStudio Python bindings and write python-api YAML + GZ files."
    )
    parser.add_argument(
        "openstudio_python_dir",
        help="Path to the OpenStudio Python directory, e.g. /Applications/OpenStudio-3.10.0/Python",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help=(
            "Directory where output files are written. "
            "Defaults to <script_dir>/docs/api/. "
            "Files are named python-api-<version>.yaml and python-api-<version>.yaml.gz."
        ),
    )
    args = parser.parse_args()

    python_dir = Path(args.openstudio_python_dir).expanduser().resolve()
    if not python_dir.exists():
        print(f"Error: {python_dir} does not exist")
        return 1

    sys.path.insert(0, str(python_dir))
    import openstudio  # noqa: PLC0415

    openstudio_version = openstudio.openStudioVersion()
    print(f"Introspecting OpenStudio {openstudio_version} Python bindings from {python_dir}")

    all_classes: Dict[str, Dict] = {}
    submodule_index: Dict[str, List[str]] = {}

    for submod_name, prefix in SUBMODULE_PREFIXES.items():
        submod = getattr(openstudio, submod_name, None)
        if submod is None:
            print(f"  Skipping {submod_name} (not found)")
            continue

        print(f"  Processing openstudio.{submod_name} ...")
        classes = extract_submodule(submod, prefix)
        print(f"    {len(classes)} classes")
        all_classes[submod_name] = classes
        submodule_index[prefix] = list(classes.keys())

    total_classes = sum(len(v) for v in all_classes.values())
    total_methods = sum(
        c['own_method_count']
        for submod in all_classes.values()
        for c in submod.values()
    )

    # Flat map: class name -> data (model takes priority for duplicates)
    flat: Dict[str, Dict] = {}
    for submod_name, classes in all_classes.items():
        for cls_name, cls_data in classes.items():
            if cls_name not in flat or submod_name == 'model':
                flat[cls_name] = cls_data

    output = {
        'metadata': {
            'openstudio_version': openstudio_version,
            'python_path': str(python_dir),
            'total_classes': total_classes,
            'total_own_methods': total_methods,
            'extraction_date': datetime.date.today().isoformat(),
            'note': 'own_methods excludes inherited methods; return types inferred from naming conventions',
        },
        'submodules': submodule_index,
        'classes': flat,
    }

    output_dir = Path(args.output_dir).expanduser().resolve() if args.output_dir else \
        Path(__file__).parent.parent / 'docs' / 'api'

    version_slug = openstudio_version.replace(' ', '_')
    out_path = output_dir / f"python-api-{version_slug}.yaml"

    print(f"\nWriting outputs to {output_dir} ...")
    _write_yaml_and_gz(output, out_path)

    size_mb = out_path.stat().st_size / 1e6
    print(f"\nDone — {size_mb:.1f} MB")
    print(f"  OpenStudio version : {openstudio_version}")
    print(f"  Total classes      : {total_classes}")
    print(f"  Total own methods  : {total_methods}")

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
